#!/bin/bash

VERSION="0.3"

#	Settings

DUMMY="/tmp/.dummy-$RANDOM"
DUMMY_SIZE="256"

TEST_ITERATIONS="3"



#	Generic Functions

function is-installed { type -P $1 &>/dev/null || { echo "$1 is missing. Please, install it." >&2; exit 1; }; }

function mk-dummy { dd if=/dev/zero of=$DUMMY bs=1MB count=$DUMMY_SIZE >/dev/null 2>&1; }

function rm-dummy { rm -f $DUMMY*; }

function diff-time { echo $1 $2 | awk '{printf("%.2f", $1-$2)}'; }

function print-dummy { echo -e "Dummy $DUMMY_SIZE mb, $TEST_ITERATIONS times\n"; }

function print-result { echo -e "\nAverage: `echo $1 $2 | awk '{printf("%.2f", $1/$2)}'`s"; }

function run-test {
	case $1 in
		compress-gz)
			is-installed gzip

			echo -e "Running GZIP Compression..\n"

			compress-generic $TEST_ITERATIONS "gzip -q $DUMMY"
			;;
		compress-xz)
			is-installed xz

			echo -e "Running XZ Compression..\n"

			compress-generic $TEST_ITERATIONS "xz -q $DUMMY"
			;;
		compress-bz2)
			is-installed bzip2

			echo -e "Running BZIP2 Compression..\n"

			compress-generic $TEST_ITERATIONS "bzip2 -q $DUMMY"
			;;
		compress-lzo)
			is-installed lzop

			echo -e "Running LZOP Compression..\n"

			compress-generic $TEST_ITERATIONS "lzop -q $DUMMY"
			;;
		compress-7z)
			is-installed 7z

			echo -e "Running 7z Compression..\n"

			compress-generic $TEST_ITERATIONS "7z -bd a $DUMMY.7z $DUMMY"
			;;
		*)
			echo -e "Test not found.\n"

			display-tests

			exit 0
			;;
	esac
}



#	Tests

function compress-generic {
	print-dummy

	for ((i=1; i <= $1; i++))
	do
		mk-dummy

		_START=`date +%s.%N`

		$2 >/dev/null 2>&1

		_STOP=`date +%s.%N`

		_RES=`diff-time $_STOP $_START`

		_AVG=`echo $_AVG $_RES | awk '{printf("%.2f", $1+$2)}'`

		echo "  #$i	$_RES"s

		rm-dummy

		sleep 2
	done

	print-result $_AVG $1
}



#	Lists

function display-version { echo -e "Pluk $VERSION\nA simple benchmarking tool."; }

function display-help {
	echo "Usage: pluk [OPTIONS] -t <TEST>"
	echo
	echo "  -h		display this help"
	echo "  -l		display available tests"
	echo "  -v              display version number"
	echo
	echo "  -n <N>          number of tests (default 3)"
	echo "  -s <N>          size of the dummy file in MB (default 256)"
	echo "  -t <test>	run specific test"
}

function display-tests {
	echo "Compress Tests"
	echo
	echo "  compress-gz             use GZIP"
	echo "  compress-xz             use XZ"
	echo "  compress-bz2            use BZIP2"
	echo "  compress-lzo            use LZOP"
	echo "  compress-7z             use 7z"
}



while getopts  "hlvs:n:t:" OPT
do

	case $OPT in
		h)
			display-help

			exit 0
			;;
		l)
			display-tests

			exit 0
			;;
		n)
			TEST_ITERATIONS=$OPTARG
			;;
		s)
			DUMMY_SIZE=$OPTARG
			;;
		t)
			run-test $OPTARG

			exit 0
			;;
		v)
			display-version

			exit 0
			;;
		*)
			display-help

			exit 0
			;;
	esac

done
